(()=>{"use strict";
const $=id=>document.getElementById(id),DB="SanskritStudioV9",VER=1;let db,docs=[],activeId=null,saveTimer,lastRange=null,dictionary=[],snapTimer;
let settings={theme:"dark",input:"direct",showIAST:true,kbdStartup:true,kbdPos:null,recent:[]};
const groups={Vowels:["अ","आ","इ","ई","उ","ऊ","ऋ","ॠ","ऌ","ॡ","ए","ऐ","ओ","औ"],Consonants:["क","ख","ग","घ","ङ","च","छ","ज","झ","ञ","ट","ठ","ड","ढ","ण","त","थ","द","ध","न","प","फ","ब","भ","म","य","र","ल","व","श","ष","स","ह"],"Mātrās & Signs":["ा","ि","ी","ु","ू","ृ","ॄ","ॢ","ॣ","े","ै","ो","ौ","्","ं","ः","ँ","़","ऽ","ॐ","।","॥"],Conjuncts:["क्ष","त्र","ज्ञ","श्र","द्य","द्व","त्व","स्त","स्व","प्र","ग्र","क्र","ब्र","भ्र"],Numbers:["०","१","२","३","४","५","६","७","८","९"]};
const cons=new Set(groups.Consonants),dm={"अ":"a","आ":"ā","इ":"i","ई":"ī","उ":"u","ऊ":"ū","ऋ":"ṛ","ॠ":"ṝ","ऌ":"ḷ","ॡ":"ḹ","ए":"e","ऐ":"ai","ओ":"o","औ":"au","क":"k","ख":"kh","ग":"g","घ":"gh","ङ":"ṅ","च":"c","छ":"ch","ज":"j","झ":"jh","ञ":"ñ","ट":"ṭ","ठ":"ṭh","ड":"ḍ","ढ":"ḍh","ण":"ṇ","त":"t","थ":"th","द":"d","ध":"dh","न":"n","प":"p","फ":"ph","ब":"b","भ":"bh","म":"m","य":"y","र":"r","ल":"l","व":"v","श":"ś","ष":"ṣ","स":"s","ह":"h","ा":"ā","ि":"i","ी":"ī","ु":"u","ू":"ū","ृ":"ṛ","ॄ":"ṝ","ॢ":"ḷ","ॣ":"ḹ","े":"e","ै":"ai","ो":"o","ौ":"au","ं":"ṃ","ः":"ḥ","ँ":"m̐","ऽ":"'","।":" |","॥":" ||"};
const indep={"a":"अ","ā":"आ","i":"इ","ī":"ई","u":"उ","ū":"ऊ","ṛ":"ऋ","ṝ":"ॠ","ḷ":"ऌ","ḹ":"ॡ","e":"ए","ai":"ऐ","o":"ओ","au":"औ"},mat={"a":"","ā":"ा","i":"ि","ī":"ी","u":"ु","ū":"ू","ṛ":"ृ","ṝ":"ॄ","ḷ":"ॢ","ḹ":"ॣ","e":"े","ai":"ै","o":"ो","au":"ौ"},cm={"k":"क","kh":"ख","g":"ग","gh":"घ","ṅ":"ङ","c":"च","ch":"छ","j":"ज","jh":"झ","ñ":"ञ","ṭ":"ट","ṭh":"ठ","ḍ":"ड","ḍh":"ढ","ṇ":"ण","t":"त","th":"थ","d":"द","dh":"ध","n":"न","p":"प","ph":"फ","b":"ब","bh":"भ","m":"म","y":"य","r":"र","l":"ल","v":"व","ś":"श","ṣ":"ष","s":"स","h":"ह"},special={"ṃ":"ं","ṁ":"ं","ḥ":"ः","m̐":"ँ","'":"ऽ","|":"।","||":"॥"};
const reqP=r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}),done=t=>new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error)});
async function initDB(){db=await new Promise((res,rej)=>{let r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains("documents"))d.createObjectStore("documents",{keyPath:"id"});if(!d.objectStoreNames.contains("trash"))d.createObjectStore("trash",{keyPath:"id"});if(!d.objectStoreNames.contains("history")){let s=d.createObjectStore("history",{keyPath:"id"});s.createIndex("docId","docId")}if(!d.objectStoreNames.contains("meta"))d.createObjectStore("meta",{keyPath:"key"})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(s){let t=db.transaction(s,"readonly");return reqP(t.objectStore(s).getAll())}async function put(s,o){let t=db.transaction(s,"readwrite");t.objectStore(s).put(o);await done(t)}async function del(s,k){let t=db.transaction(s,"readwrite");t.objectStore(s).delete(k);await done(t)}async function mget(k){let t=db.transaction("meta","readonly");return reqP(t.objectStore("meta").get(k))}async function mput(k,v){return put("meta",{key:k,value:v})}
const uid=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,now=()=>new Date().toISOString(),active=()=>docs.find(d=>d.id===activeId),esc=s=>s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function createDoc(title){let d={id:uid("doc"),title:title||`Untitled ${docs.length+1}`,html:"",createdAt:now(),updatedAt:now(),order:docs.length};docs.push(d);activeId=d.id;await put("documents",d);await mput("activeId",activeId);renderTabs();loadDoc()}
async function load(){docs=(await all("documents")).sort((a,b)=>(a.order||0)-(b.order||0));let a=await mget("activeId"),s=await mget("settings");if(s?.value)settings={...settings,...s.value};if(!docs.length)await createDoc("Untitled 1");else{activeId=a?.value&&docs.some(d=>d.id===a.value)?a.value:docs[0].id;renderTabs();loadDoc()}applySettings()}
function renderTabs(){let b=$("docTabs");b.innerHTML="";docs.forEach(d=>{let t=document.createElement("div");t.className="doctab"+(d.id===activeId?" active":"");let n=document.createElement("span");n.textContent=d.title;n.ondblclick=()=>rename(d);let x=document.createElement("button");x.className="x";x.textContent="×";x.onclick=e=>{e.stopPropagation();trash(d.id)};t.onclick=()=>switchDoc(d.id);t.append(n,x);b.append(t)})}
async function switchDoc(id){await saveNow();activeId=id;await mput("activeId",id);renderTabs();loadDoc()}function loadDoc(){$("editor").innerHTML=active()?.html||"";update()}
async function rename(d){let n=prompt("Rename document:",d.title);if(n&&n.trim()){d.title=n.trim();d.updatedAt=now();await put("documents",d);renderTabs()}}
async function trash(id){let d=docs.find(x=>x.id===id);if(!d)return;if(d.id===activeId)await saveNow();await put("trash",{...d,deletedAt:now()});await del("documents",id);docs=docs.filter(x=>x.id!==id);if(!docs.length)await createDoc("Untitled 1");else{if(activeId===id)activeId=docs[0].id;await mput("activeId",activeId);renderTabs();loadDoc()}}
function saveState(t){$("saveStatus").textContent=t}function schedule(){saveState("Saving…");clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,400)}async function saveNow(){let d=active();if(!d)return;d.html=$("editor").innerHTML;d.updatedAt=now();await put("documents",d);saveState("Saved locally ✓")}
function textOf(html){let d=document.createElement("div");d.innerHTML=html;return d.innerText||""}function update(){let t=$("editor").innerText||"";$("stats").textContent=`${t.trim()?t.trim().split(/\s+/).length:0} words • ${Array.from(t).length} characters`;$("iastView").value=toIAST(t)}
async function snapshot(force=false){let d=active();if(!d)return;let h=(await all("history")).filter(x=>x.docId===d.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),html=$("editor").innerHTML;if(!force&&h[0]?.html===html)return;await put("history",{id:uid("hist"),docId:d.id,html,createdAt:now()});h=(await all("history")).filter(x=>x.docId===d.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));for(let x of h.slice(25))await del("history",x.id)}
function saveSel(){let s=getSelection();if(s&&s.rangeCount&&$("editor").contains(s.anchorNode))lastRange=s.getRangeAt(0).cloneRange()}function restoreSel(){if(!lastRange)return;let s=getSelection();s.removeAllRanges();s.addRange(lastRange)}function insertText(t){$("editor").focus();restoreSel();document.execCommand("insertText",false,t);schedule();update()}
function normalize(t){return t.normalize("NFC").replace(/aa/g,"ā").replace(/ii/g,"ī").replace(/uu/g,"ū").replace(/\.r/g,"ṛ").replace(/\.R/g,"ṝ").replace(/\.l/g,"ḷ").replace(/~n/g,"ñ").replace(/"n/g,"ṅ").replace(/\.n/g,"ṇ").replace(/\.s/g,"ṣ").replace(/sh/g,"ś").replace(/\.m/g,"ṃ").replace(/\.h/g,"ḥ")}
function toDeva(text){text=normalize(text);let V=["ai","au","ā","ī","ū","ṝ","ḹ","ṛ","ḷ","e","o","a","i","u"],C=["kh","gh","ch","jh","ṭh","ḍh","th","dh","ph","bh","ṅ","ñ","ṭ","ḍ","ṇ","ś","ṣ","k","g","c","j","t","d","n","p","b","m","y","r","l","v","s","h"],o="",i=0,p=false,m=a=>a.find(x=>text.startsWith(x,i));while(i<text.length){let c=text[i];if(/\s/.test(c)){p=false;o+=c;i++;continue}if(text.startsWith("||",i)){o+="॥";i+=2;p=false;continue}if(c==="|"){o+="।";i++;p=false;continue}let x=m(C);if(x){if(p)o+="्";o+=cm[x];i+=x.length;p=true;continue}let v=m(V);if(v){o+=p?(mat[v]||""):(indep[v]||v);i+=v.length;p=false;continue}let sk=Object.keys(special).sort((a,b)=>b.length-a.length).find(x=>text.startsWith(x,i));if(sk){o+=special[sk];i+=sk.length;p=false;continue}p=false;o+=c;i++}return o}
function toIAST(text){let a=Array.from(text),o="";for(let i=0;i<a.length;i++){let c=a[i];if(cons.has(c)){let n=a[i+1];if(n==="्"){o+=dm[c]||c;i++;continue}if(n&&["ा","ि","ी","ु","ू","ृ","ॄ","ॢ","ॣ","े","ै","ो","ौ"].includes(n)){o+=(dm[c]||c)+(dm[n]||"");i++;continue}o+=(dm[c]||c)+"a";continue}if(c==="्")continue;o+=dm[c]??c}return o}
function renderKbd(){let root=$("keyGroups");root.innerHTML="";Object.entries(groups).forEach(([name,arr])=>{let g=document.createElement("div");g.className="keygroup";g.innerHTML=`<h4>${name}</h4><div class="keys"></div>`;arr.forEach(ch=>{let b=document.createElement("button");b.className="skey";b.textContent=ch;b.onclick=()=>{insertText(ch);settings.recent=[ch,...settings.recent.filter(x=>x!==ch)].slice(0,10);renderRecent();saveSettings()};g.querySelector(".keys").append(b)});root.append(g)});renderRecent()}
function renderRecent(){let r=$("recentKeys");r.innerHTML="";settings.recent.forEach(ch=>{let b=document.createElement("button");b.className="skey";b.textContent=ch;b.onclick=()=>insertText(ch);r.append(b)})}
async function loadDict(){try{let r=await fetch("dictionary.json",{cache:"no-store"});dictionary=await r.json();$("dictMeta").textContent=`${dictionary.length.toLocaleString()} local entries loaded`}catch{$("dictMeta").textContent="dictionary.json could not be loaded"}}
function clean(q){return q.trim().replace(/[।॥,.;:!?'"“”‘’()[\]{}]/g,"")}function search(q){q=clean(q);let qi=normalize(q.toLowerCase()),qd=/[\u0900-\u097F]/.test(q)?q:toDeva(qi),res=dictionary.map(e=>{let w=e.word||"",i=(e.iast||toIAST(w)).toLowerCase(),s=0;if(w===qd||i===qi)s=100;else if(w.startsWith(qd)||i.startsWith(qi))s=80;else if(w.includes(qd)||i.includes(qi))s=60;else if((e.meaning||"").toLowerCase().includes(q.toLowerCase()))s=20;return{e,s}}).filter(x=>x.s).sort((a,b)=>b.s-a.s).slice(0,50).map(x=>x.e);renderResults(res,q)}
function renderResults(res,q=""){let b=$("dictResults");b.innerHTML="";if(!res.length){b.innerHTML=`<div class="dictcard">${q?`No matches for <b>${esc(q)}</b>.`:"Search for a Sanskrit word."}</div>`;return}res.forEach(e=>{let c=document.createElement("div");c.className="dictcard";c.innerHTML=`<div class="dictword">${esc(e.word||"")}</div><div class="dictiast">${esc(e.iast||toIAST(e.word||""))}</div>${e.grammar?`<div class="dictsource">${esc(e.grammar)}</div>`:""}<div class="dictmeaning">${esc(e.meaning||"")}</div><div class="dictsource">${esc(e.source||"Local dictionary")}</div><div class="dictactions"><button class="primary ins">Insert into document</button><button class="cpy">Copy</button></div>`;c.querySelector(".ins").onclick=()=>{showWrite();insertText(e.word||"")};c.querySelector(".cpy").onclick=()=>navigator.clipboard.writeText(`${e.word} — ${e.meaning}`);b.append(c)})}
function selText(){return clean(getSelection()?.toString()||"")}function lookupSel(){let q=selText();if(!q)return alert("Select a Sanskrit word first.");$("dictQuery").value=q;showDict();search(q)}
function showWrite(){$("writeView").classList.add("active");$("dictView").classList.remove("active");$("navWrite").classList.add("active");$("navDict").classList.remove("active")}function showDict(){$("writeView").classList.remove("active");$("dictView").classList.add("active");$("navWrite").classList.remove("active");$("navDict").classList.add("active");$("dictQuery").focus()}
function modal(id){$("backdrop").classList.remove("hidden");$(id).classList.remove("hidden")}function closeModals(){$("backdrop").classList.add("hidden");document.querySelectorAll(".modal").forEach(m=>m.classList.add("hidden"))}
async function showTrash(){let b=$("trashList"),a=(await all("trash")).sort((x,y)=>y.deletedAt.localeCompare(x.deletedAt));b.innerHTML=a.length?"":"<p>Trash is empty.</p>";a.forEach(d=>{let r=document.createElement("div");r.className="listitem";r.innerHTML=`<div><b>${esc(d.title)}</b><br><small>${new Date(d.deletedAt).toLocaleString()}</small></div><div><button class="restore">Restore</button><button class="forever">Delete forever</button></div>`;r.querySelector(".restore").onclick=async()=>{delete d.deletedAt;d.order=docs.length;await put("documents",d);await del("trash",d.id);docs.push(d);renderTabs();showTrash()};r.querySelector(".forever").onclick=async()=>{if(confirm("Delete forever?")){await del("trash",d.id);showTrash()}};b.append(r)})}
async function showHistory(){await snapshot(true);let d=active(),a=(await all("history")).filter(x=>x.docId===d.id).sort((x,y)=>y.createdAt.localeCompare(x.createdAt)),b=$("historyList");b.innerHTML=a.length?"":"<p>No snapshots yet.</p>";a.forEach(h=>{let r=document.createElement("div");r.className="listitem",p=textOf(h.html).slice(0,80);r.innerHTML=`<div><b>${new Date(h.createdAt).toLocaleString()}</b><br><small>${esc(p)}${p.length===80?"…":""}</small></div><button>Restore</button>`;r.querySelector("button").onclick=async()=>{if(confirm("Restore this snapshot?")){await snapshot(true);$("editor").innerHTML=h.html;schedule();update();closeModals()}};b.append(r)})}
function dl(name,blob){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function safe(s){return(s||"Sanskrit Document").replace(/[\\/:*?"<>|]/g,"-")}
function exportDoc(type){let d=active(),html=$("editor").innerHTML,text=$("editor").innerText||"",n=safe(d.title);if(type==="txt")dl(n+".txt",new Blob([text],{type:"text/plain"}));if(type==="html")dl(n+".html",new Blob([`<!doctype html><meta charset=utf-8><title>${esc(d.title)}</title>${html}`],{type:"text/html"}));if(type==="doc")dl(n+".doc",new Blob([`<!doctype html><meta charset=utf-8><body style="font-family:serif;font-size:18pt">${html}</body>`],{type:"application/msword"}));if(type==="pdf"){let w=open("","_blank");if(w){w.document.write(`<meta charset=utf-8><style>body{font-family:serif;font-size:20px;line-height:1.7;padding:40px}</style>${html}`);w.document.close();setTimeout(()=>w.print(),250)}}closeModals()}
async function exportWorkspace(){await saveNow();let p={format:"SanskritStudioV9",exportedAt:now(),documents:await all("documents"),trash:await all("trash"),history:await all("history"),settings};dl("sanskrit-studio-workspace.json",new Blob([JSON.stringify(p,null,2)],{type:"application/json"}))}
async function importWorkspace(f){let p;try{p=JSON.parse(await f.text())}catch{return alert("Invalid JSON")}if(p.format!=="SanskritStudioV9")return alert("Not a V9 workspace.");for(let d of p.documents||[])await put("documents",d);for(let d of p.trash||[])await put("trash",d);for(let h of p.history||[])await put("history",h);if(p.settings){settings={...settings,...p.settings};await saveSettings()}docs=(await all("documents")).sort((a,b)=>(a.order||0)-(b.order||0));activeId=docs[0]?.id;await mput("activeId",activeId);applySettings();renderTabs();loadDoc();alert("Workspace imported.")}
async function saveSettings(){await mput("settings",settings)}function applySettings(){document.documentElement.dataset.theme=settings.theme;$("themeSet").value=settings.theme;$("inputSet").value=settings.input;$("iastSet").checked=settings.showIAST;$("kbdSet").checked=settings.kbdStartup;$("iastPane").classList.toggle("hidden",!settings.showIAST);$("inputMode").value=settings.input;toggleRoman();if(!settings.kbdStartup)$("keyboard").classList.add("hidden");else $("keyboard").classList.remove("hidden");if(settings.kbdPos&&innerWidth>700){$("keyboard").style.left=settings.kbdPos.left+"px";$("keyboard").style.top=settings.kbdPos.top+"px";$("keyboard").style.bottom="auto"}renderRecent()}
function toggleRoman(){$("romanPanel").classList.toggle("hidden",$("inputMode").value!=="roman")}function dragInit(){let w=$("keyboard"),h=$("dragHandle"),drag=false,ox=0,oy=0;h.onpointerdown=e=>{if(e.target.closest("button")||innerWidth<700)return;drag=true;let r=w.getBoundingClientRect();ox=e.clientX-r.left;oy=e.clientY-r.top;w.style.bottom="auto";h.setPointerCapture(e.pointerId)};h.onpointermove=e=>{if(!drag)return;let l=Math.max(4,Math.min(innerWidth-w.offsetWidth-4,e.clientX-ox)),t=Math.max(64,Math.min(innerHeight-w.offsetHeight-4,e.clientY-oy));w.style.left=l+"px";w.style.top=t+"px"};h.onpointerup=async()=>{if(drag){drag=false;let r=w.getBoundingClientRect();settings.kbdPos={left:r.left,top:r.top};await saveSettings()}}}
function events(){$("editor").addEventListener("input",()=>{schedule();update();saveSel()});["keyup","mouseup","focus"].forEach(e=>$("editor").addEventListener(e,saveSel));$("editor").oncontextmenu=e=>{let q=selText();if(!q)return;e.preventDefault();saveSel();let m=$("contextMenu");m.style.left=e.clientX+"px";m.style.top=e.clientY+"px";m.classList.remove("hidden")};document.addEventListener("click",e=>{if(!e.target.closest("#contextMenu"))$("contextMenu").classList.add("hidden")});
document.querySelectorAll("[data-cmd]").forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd);schedule();update()});$("highlightBtn").onclick=()=>document.execCommand("hiliteColor",false,"#fff08b");$("clearFmtBtn").onclick=()=>document.execCommand("removeFormat");$("inputMode").onchange=toggleRoman;$("romanInput").oninput=e=>$("romanPreview").textContent=toDeva(e.target.value);$("romanInsert").onclick=()=>insertText(toDeva($("romanInput").value));$("romanReplace").onclick=()=>{restoreSel();document.execCommand("insertText",false,toDeva($("romanInput").value));schedule();update()};$("romanClear").onclick=()=>{$("romanInput").value="";$("romanPreview").textContent=""};
$("newDoc").onclick=()=>createDoc();$("trashBtn").onclick=async()=>{await showTrash();modal("trashModal")};$("historyBtn").onclick=async()=>{await showHistory();modal("historyModal")};$("exportBtn").onclick=()=>modal("exportModal");document.querySelectorAll("[data-export]").forEach(b=>b.onclick=()=>exportDoc(b.dataset.export));$("navWrite").onclick=showWrite;$("navDict").onclick=showDict;$("dictSearch").onclick=()=>search($("dictQuery").value);$("dictQuery").onkeydown=e=>{if(e.key==="Enter")search(e.target.value)};$("lookupBtn").onclick=lookupSel;$("ctxLookup").onclick=lookupSel;$("ctxCopy").onclick=()=>navigator.clipboard.writeText(selText());
$("kbdBtn").onclick=()=>$("keyboard").classList.toggle("hidden");$("closeKbd").onclick=()=>$("keyboard").classList.add("hidden");$("minKbd").onclick=()=>$("keyboard").classList.toggle("minimized");$("settingsBtn").onclick=()=>modal("settingsModal");$("helpBtn").onclick=()=>$("helpDrawer").classList.add("open");$("closeHelp").onclick=()=>$("helpDrawer").classList.remove("open");$("backdrop").onclick=closeModals;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closeModals);$("copyIAST").onclick=()=>navigator.clipboard.writeText($("iastView").value);$("focusBtn").onclick=()=>document.body.classList.toggle("focus");
$("themeSet").onchange=async e=>{settings.theme=e.target.value;await saveSettings();applySettings()};$("inputSet").onchange=async e=>{settings.input=e.target.value;await saveSettings()};$("iastSet").onchange=async e=>{settings.showIAST=e.target.checked;await saveSettings();applySettings()};$("kbdSet").onchange=async e=>{settings.kbdStartup=e.target.checked;await saveSettings()};$("exportWorkspace").onclick=exportWorkspace;$("importWorkspace").onchange=e=>{let f=e.target.files?.[0];if(f)importWorkspace(f)};
$("helpSearch").oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll("#helpContent section").forEach(s=>s.classList.toggle("hidden",q&&!s.innerText.toLowerCase().includes(q)))};addEventListener("keydown",e=>{let m=e.metaKey||e.ctrlKey;if(m&&e.key.toLowerCase()==="s"){e.preventDefault();saveNow()}if(m&&e.key.toLowerCase()==="n"){e.preventDefault();createDoc()}if(m&&e.key.toLowerCase()==="k"){e.preventDefault();$("keyboard").classList.toggle("hidden")}if(m&&e.shiftKey&&e.key.toLowerCase()==="d"){e.preventDefault();lookupSel()}})}
async function start(){await initDB();await loadDict();renderKbd();dragInit();events();await load();renderResults([]);snapTimer=setInterval(()=>snapshot(false),60000)}start().catch(e=>{console.error(e);alert("Sanskrit Studio could not initialize local storage.")});
})();